/**
 * @file generated_log_tags.hpp
 * @brief Auto-generated list of logging tags
 *
 * This file is automatically generated by tools/generate_log_tags.py
 * during the build process. DO NOT EDIT MANUALLY.
 *
 * To regenerate, run: cmake --build build
 */

#pragma once

#include <cstddef>

namespace ui {

// Auto-generated list of all known logging tags in the codebase
static const char* KNOWN_LOG_TAGS[] = {
    "ConfigStorage",
    "HttpServer",
    "LedDriver",
    "PaddleHal",
    "RemoteCwClient",
    "SerialConsole",
    "SidetoneService",
    "TimelineEmitter",
    "TxHal",
    "WiFiSubsystem",
    "app",
    "audio_subsystem",
    "boot_failure",
    "bootloader_entry",
    "console_param_bridge",
    "console_system",
    "diagnostics_subsystem",
    "init_phases",
    "init_pipeline",
    "keying_subsystem",
    "morse_decoder",
    "morse_encoder",
    "morse_table",
    "paddle_engine",
    "param_registry",
    "remote_server",
    "text_keyer",
    "usb_early",

};

static constexpr size_t KNOWN_LOG_TAGS_COUNT = sizeof(KNOWN_LOG_TAGS) / sizeof(KNOWN_LOG_TAGS[0]);

}  // namespace ui
